using System;
using System.Collections.Generic;
using System.Text;

namespace STUWard;

internal readonly struct ManagedWardReportAccountEntry
{
    internal ManagedWardReportAccountEntry(string accountId, int wardCount, int effectiveLimit, bool hasOverride)
    {
        AccountId = accountId ?? string.Empty;
        WardCount = wardCount;
        EffectiveLimit = effectiveLimit;
        HasOverride = hasOverride;
    }

    internal string AccountId { get; }
    internal int WardCount { get; }
    internal int EffectiveLimit { get; }
    internal bool HasOverride { get; }
}

internal readonly struct ManagedWardReportSnapshot
{
    internal ManagedWardReportSnapshot(
        string modName,
        DateTime generatedAtUtc,
        string worldName,
        long worldUid,
        int totalTrackedWards,
        List<ManagedWardReportAccountEntry> accounts,
        List<KeyValuePair<long, int>> unresolvedWardOwnerCounts,
        List<KeyValuePair<long, int>> playerAccountMapGapCounts)
    {
        ModName = modName ?? string.Empty;
        GeneratedAtUtc = generatedAtUtc;
        WorldName = worldName ?? string.Empty;
        WorldUid = worldUid;
        TotalTrackedWards = totalTrackedWards;
        Accounts = accounts ?? [];
        UnresolvedWardOwnerCounts = unresolvedWardOwnerCounts ?? [];
        PlayerAccountMapGapCounts = playerAccountMapGapCounts ?? [];
    }

    internal string ModName { get; }
    internal DateTime GeneratedAtUtc { get; }
    internal string WorldName { get; }
    internal long WorldUid { get; }
    internal int TotalTrackedWards { get; }
    internal List<ManagedWardReportAccountEntry> Accounts { get; }
    internal List<KeyValuePair<long, int>> UnresolvedWardOwnerCounts { get; }
    internal List<KeyValuePair<long, int>> PlayerAccountMapGapCounts { get; }
}

internal readonly struct ManagedWardReportBuildResult
{
    internal ManagedWardReportBuildResult(string contents, int trackedAccounts, int totalWards, int unresolvedOwners)
    {
        Contents = contents ?? string.Empty;
        TrackedAccounts = trackedAccounts;
        TotalWards = totalWards;
        UnresolvedOwners = unresolvedOwners;
    }

    internal string Contents { get; }
    internal int TrackedAccounts { get; }
    internal int TotalWards { get; }
    internal int UnresolvedOwners { get; }
}

internal static class ManagedWardReportBuilder
{
    internal static ManagedWardReportBuildResult Build(ManagedWardReportSnapshot snapshot)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"# Generated by {snapshot.ModName}");
        builder.AppendLine($"# Generated at UTC: {snapshot.GeneratedAtUtc:O}");
        builder.AppendLine($"# World: {snapshot.WorldName}");
        builder.AppendLine($"# World UID: {snapshot.WorldUid}");

        builder.AppendLine("accounts:");
        if (snapshot.Accounts.Count == 0)
        {
            builder.AppendLine("  {}");
        }
        else
        {
            for (var index = 0; index < snapshot.Accounts.Count; index++)
            {
                var account = snapshot.Accounts[index];
                builder.AppendLine($"  {FormatYamlScalar(account.AccountId)}:");
                builder.AppendLine($"    wards: {account.WardCount}");
                builder.AppendLine($"    limit: {account.EffectiveLimit}");
                builder.AppendLine($"    override: {account.HasOverride.ToString().ToLowerInvariant()}");
            }
        }

        AppendWardCountSection(builder, "unresolved_wards_by_creator_id", snapshot.UnresolvedWardOwnerCounts);
        AppendWardCountSection(builder, "player_account_map_gaps", snapshot.PlayerAccountMapGapCounts);

        return new ManagedWardReportBuildResult(
            builder.ToString(),
            snapshot.Accounts.Count,
            snapshot.TotalTrackedWards,
            CountWardEntries(snapshot.UnresolvedWardOwnerCounts));
    }

    private static void AppendWardCountSection(StringBuilder builder, string sectionName, List<KeyValuePair<long, int>> entries)
    {
        builder.AppendLine(sectionName + ":");
        if (entries.Count == 0)
        {
            builder.AppendLine("  {}");
            return;
        }

        for (var index = 0; index < entries.Count; index++)
        {
            var entry = entries[index];
            builder.AppendLine($"  {entry.Key}: {entry.Value}");
        }
    }

    private static int CountWardEntries(List<KeyValuePair<long, int>> entries)
    {
        var total = 0;
        for (var index = 0; index < entries.Count; index++)
        {
            total += Math.Max(0, entries[index].Value);
        }

        return total;
    }

    private static string FormatYamlScalar(string value)
    {
        var escapedValue = (value ?? string.Empty).Replace("'", "''");
        return $"'{escapedValue}'";
    }
}
